### PR TITLE
checkout branch and added podspec

### PR DESCRIPTION
**Pull request by jaspervp**
@thoutbeckers   I cannot test this, because travis doesn't work on my fork

### CODE REVIEW

**Comment by jaspervp** [comment]
@thoutbeckers it works if you add a GIT_TOKEN to travis.

**Comment by thoutbeckers** [comment]
Well that worked https://github.com/thoutbeckers/LeBlue/commit/dd83f5587dfd4841b2100dc8bd1baeee9b954d5f

**Comment by thoutbeckers** [comment]
I wonder if there's any way to have j2objc not put that full path in there though.

**Comment by jaspervp** [comment]
There is an gradle task in unified which removes the first 4 lines.

Op 9 aug. 2016 18:51 schreef "Tijl" <notifications@github.com>:

**Pull request merged**
